In [1]:
import gym
import pylab
import random
import numpy as np
from collections import deque
import tflearn
import tensorflow as tf
import keras
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation
from keras.optimizers import Adagrad


gpu_options = tf.GPUOptions(per_process_gpu_memory_fraction=0.333)
cpu_options = tf.CPUOptions(per_process_cpu_memory_fraction=0.333)

Using TensorFlow backend.


AttributeError: module 'tensorflow' has no attribute 'CPUOptions'

## Task: fill empty spaces in the following agent code

In [2]:
class DeepQAgent:
    def __init__(self, state_size, action_size, render=True):
        # Tip: if you are training this on AWS the best way is to turn off rendering
        # and load it later with the serialized model
        self.render = render
        self.state_size = state_size
        self.action_size = action_size

        self.discount_factor = 0.99
        self.learning_rate = 0.001
        self.epsilon = 1.0
        self.epsilon_min = 0.005
        self.epsilon_decay = (self.epsilon - self.epsilon_min) / 50000
        self.batch_size = 64
        self.train_start = 1000
        # replay memory
        self.memory = deque(maxlen=10000)

        self.model = self.build_model()
        self.target_model = self.build_model()
        self.update_target_model()

    def build_model(self):
        model = Sequential()
        model.add(Dense(10, activation='relu', input_dim = self.state_size))
        model.add(Dense(self.action_size, activation='softmax'))
        
        adagrad = Adagrad(lr=self.learning_rate)
        model.compile(loss='categorical_crossentropy',
              optimizer=adagrad,
              metrics=['accuracy'])
        return model

    def update_target_model(self):
        print("update")
        """Update your target model to the model you are currently learning at regular time intervals"""        
        self.target_model.set_weights(self.model.get_weights())


    def get_action(self, state):
        """The choice of action uses the epsilon-greedy policy for the current network."""
        if np.random.rand() <= self.epsilon:
            if (state[0][0] < -0.6 and state[0][1] < -0.01):
                return 0
            elif (state[0][0] > -0.4 and state[0][1] > 0.01):
                return 1
            elif (state[0][0] < -0.6 and state[0][1] > -0.01):
                return 1
            elif (state[0][0] > -0.4 and state[0][1] < 0.01):
                return 0
            elif (state[0][0] > -0.6 and state[0][0] < -0.4 and state[0][1] < 0):
                return 0
            elif (state[0][0] > -0.6 and state[0][0] < -0.4 and state[0][1] > 0):
                return 1
            
            return random.randrange(self.action_size)
        else:
            q_value = self.model.predict(state)
            return np.argmax(q_value[0])

    def replay_memory(self, state, action, reward, next_state, done):
        """Save <s, a, r, s'> to replay_memory"""
        if action == 2:
            action = 1
        self.memory.append((state, action, reward, next_state, done))
        if self.epsilon > self.epsilon_min:
            self.epsilon -= self.epsilon_decay
            # print(len(self.memory))

    def train_replay(self):
        """Random sampling of batch_size samples from replay memory"""
        if len(self.memory) < self.train_start:
            return
        batch_size = min(self.batch_size, len(self.memory))
        mini_batch = random.sample(self.memory, batch_size)

        update_input = np.zeros((batch_size, self.state_size))
        update_target = np.zeros((batch_size, self.action_size))

        for i in range(batch_size):
            state, action, reward, next_state, done = mini_batch[i]
            target = self.model.predict(state)[0]

            # As in queuing, it gets the maximum Q Value at s'. However, it is imported from the target model.
            if done:
                target[action] = reward
            else:
                target[action] = reward + self.discount_factor * \
                                          np.amax(self.target_model.predict(next_state)[0])
            update_input[i] = state
            update_target[i] = target

        # You can create a minibatch of the correct target answer and the current value of your own,
        self.model.fit(update_input, update_target, batch_size=batch_size, epochs=1, verbose=0)

    def load_model(self, name):
        self.model.load_model(name)

    def save_model(self, name):
        self.model.save(name)


In [3]:
env = gym.make('MountainCar-v0')
state_size = env.observation_space.shape[0] # should be equal 2
ACTION_SIZE = 2
agent = DeepQAgent(state_size, ACTION_SIZE)
#agent.load_model("./save_model/model")
scores, episodes = [], []
N_EPISODES = 4000

update


In [4]:
for e in range(N_EPISODES):
    done = False
    score = 0
    state = env.reset()
    state = np.reshape(state, [1, state_size])
    print("state", state)

    # Action 0 (left), 1 (do nothing), 3 (declare fake_action to avoid doing nothing
    fake_action = 0

    # Counter for the same action 4 times
    action_count = 0

    while not done:
        if agent.render:
            env.render()

        # Select an action in the current state and proceed to a step
        action_count = action_count + 1

        if action_count == 4:
            action = agent.get_action(state)
            action_count = 0

            if action == 0:
                fake_action = 0
            elif action == 1:
                fake_action = 2

        # Take 1 step with the selected action
        next_state, reward, done, info = env.step(fake_action)
        next_state = np.reshape(next_state, [1, state_size])
        # Give a penalty of -100 for actions that end an episode
        # reward = reward if not done else -100

        # Save <s, a, r, s'> to replay memory
        agent.replay_memory(state, fake_action, reward, next_state, done)
        # Continue to learn every time step
        agent.train_replay()
        score += reward
        state = next_state

        if done:
            env.reset()
            # Copy the learning model for each episode to the target model
            agent.update_target_model()

            # For each episode, the time step where cartpole stood is plot
            scores.append(score)
            episodes.append(e)
            print("episode:", e, "  score:", score, "  memory length:", len(agent.memory),
                  "  epsilon:", agent.epsilon)

    # Save model for every 50 episodes
    if e % 50 == 0:
        agent.save_model("./save_model/model")

state [[-0.42618867  0.        ]]
[[-0.43644821 -0.00511124]]
[[-0.47280497 -0.01135408]]
[[-0.53102032 -0.01626486]]
[[-0.60420776 -0.01924799]]
[[-0.68379855 -0.02000606]]
[[-0.76099877 -0.01862991]]
[[-0.82822767 -0.01553181]]
[[-0.87995059 -0.01125657]]
[[-0.91273456 -0.00630067]]
[[-0.90490461  0.00691058]]
[[-0.84490299  0.01976031]]
[[-0.73647251  0.03126155]]
[[-0.58877065  0.03984665]]
[[-0.41764795  0.04390838]]
[[-0.24278938  0.04302823]]
[[-0.08110006  0.03854208]]
[[ 0.05843703  0.03264571]]
[[ 0.17500176  0.02717435]]
[[ 0.27314496  0.02317539]]
[[ 0.36006784  0.02112488]]
[[ 0.44421632  0.02127402]]
update
episode: 0   score: -86.0   memory length: 86   epsilon: 0.9999828859999971
state [[-0.59343473  0.        ]]
[[-0.59629747 -0.00142611]]
[[-0.60643864 -0.00316683]]
[[-0.60290303  0.00331326]]
[[-0.57417347  0.00940937]]
[[-0.52360838  0.01440049]]
[[-0.45719085  0.01768383]]
[[-0.38273489  0.01890556]]
[[-0.30861564  0.0180595 ]]
[[-0.24239832  0.01546078]]
[[-0.1899

KeyboardInterrupt: 